# Encoder Hyperparameters
encoder: tdnn_conformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024  
    num_blocks: 6 
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.0
    input_layer: conv2d
    normalize_before: true
    
    # TDNN specific parameters
    tdnn_module_kernel: 3
    tdnn_module_dilation: 1
    tdnn_module_context_size: 2
    use_tdnn_norm: "batch_norm"
    causal: false
    
    activation_type: 'swish'
    pos_enc_layer_type: 'rel_pos'
    selfattention_layer_type: 'rel_selfattn'

# Decoder Hyperparameters
decoder: transformer
decoder_conf:
    attention_heads: 4
    linear_units: 2048
    num_blocks: 6
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.0
    src_attention_dropout_rate: 0.0

# Tokenizer 
tokenizer: bpe
tokenizer_conf:
  symbol_table_path: 'data/lang_char/train_clean_100_unigram5000_units.txt'
  split_with_space: false
  bpe_path: 'data/lang_char/train_clean_100_unigram5000.model'
  non_lang_syms_path: null
  is_multilingual: false
  num_languages: 1
  special_tokens:
    <blank>: 0
    <unk>: 1
    <sos>: 2
    <eos>: 2

ctc: ctc
ctc_conf:
  ctc_blank_id: 0

cmvn: global_cmvn
cmvn_conf:
  cmvn_file: 'data/train_clean_100/global_cmvn'
  is_json_cmvn: true

# Hybrid CTC/Attention 
model: asr_model
model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

# Dataset Configuration
dataset: asr
dataset_conf:
    filter_conf:
        max_length: 2000
        min_length: 50
        token_max_length: 400
        token_min_length: 1
    resample_conf:
        resample_rate: 16000
    speed_perturb: true
    fbank_conf:
        num_mel_bins: 80
        frame_shift: 10
        frame_length: 25
        dither: 0.0
    spec_aug: true
    spec_aug_conf:
        num_t_mask: 2
        num_f_mask: 2
        max_t: 50
        max_f: 10
    shuffle: true
    shuffle_conf:
        shuffle_size: 1500
    sort: true
    sort_conf:
        sort_size: 500
    batch_conf:
        batch_type: 'static'
        batch_size: 12

grad_clip: 10
accum_grad: 1
max_epoch: 10
save_interval: 1000
log_interval: 100

optim: adam
optim_conf:
    lr: 0.001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000